before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: 64-bit
    386: 32-bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
